project:
  type: default
  output-dir: solo_build
  render:
    - "*.qmd"
    - "!index.qmd"

execute:
  freeze: auto

format:
  html:
    embed-resources: true
    toc: true
    page-navigation: false
    page-layout: article
